---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r message=FALSE, warning=FALSE, include=FALSE}
date()
setwd("/Users/magalhae/Desktop/Atshuhiro/CutandRUN/")
library(tidyverse)
library(ChIPQC)
library(ChIPseeker)
library(clusterProfiler)
library(AnnotationDbi)
library(AnnotationHub)
library(ensembldb)
library(Rsamtools)
library(Signac)
#library(TxDb.Hsapiens.UCSC.hg38.knownGene)
#library(TxDb.Mmusculus.UCSC.mm10.knownGene)
library(TxDb.Mmusculus.UCSC.mm39.knownGene)
library(ChIPpeakAnno)
```
```{r}
samples = read_csv('samples.csv', comment = '#')
blacklist <- "/Users/magalhae/Desktop/Atshuhiro/CutandRUN/mm39.excluderanges.bed"
```

```{r}
txdb <- TxDb.Mmusculus.UCSC.mm39.knownGene
annoDataTxDb <- toGRanges(TxDb.Mmusculus.UCSC.mm39.knownGene)
head(annoDataTxDb, n=2)
```
```{r}
# Load data
#samplefiles <- list.files("./04_called_peaks/seacr", pattern= ".bed", full.names=T)
samplefiles <- as.list(samples$Peaks)
names(samplefiles) <- as.list(samples$SampleID)
```
```{r}
chipObj <- ChIPQC(samples, annotation="mm10",blacklist=blacklist) 
```
```{r}
## Create ChIPQC report
ChIPQCreport(chipObj, reportName="ChIP QC report: CutandRun Mathep", reportFolder="ChIPQCreport")
```


```{r}
peakAnnoList <- lapply(samplefiles, annotatePeak, TxDb=txdb, 
                       tssRegion=c(-2000, 1000), verbose=TRUE, annoDb="org.Mm.eg.db")
```

```{r}
plotAnnoBar(peakAnnoList)
ggsave("plotAnnoBar.pdf")
```
```{r}
plotDistToTSS(peakAnnoList, title="Distribution of transcription factor-binding loci \n relative to TSS")
ggsave("plotDistToTSS.pdf")
```
```{r}
annot_peaks <- lapply(peakAnnoList, as.data.frame)
```

```{r}
library(openxlsx)
# create workbook
wb <- createWorkbook()

#Iterate the same way as PavoDive, slightly different (creating an anonymous function inside Map())
Map(function(data, nameofsheet){     

    addWorksheet(wb, nameofsheet)
    writeData(wb, nameofsheet, data)

}, annot_peaks, names(annot_peaks))

## Save workbook to excel file 
saveWorkbook(wb, file = "Peak_annotation.xlsx", overwrite = TRUE)
```

```{r}
ChIPseeker::upsetplot(peakAnnoList, vennpie=TRUE)
```

