---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r message=FALSE, warning=FALSE}
library(biomaRt)
library(SARTools)
library(DESeq2)
library(tidyverse)
library(RColorBrewer)
library(pheatmap)
library(UpSetR)
library(Seurat)
library(cowplot)
library(org.Mm.eg.db)
library("colorspace")
```
```{r}
targetFile <- "target_adult.txt" 
varInt <- "Treatment"                                    # factor of interest
condRef <- "E15"                                      # reference biological condition
batch <- NULL

colors <- c("#B80000", "#E81E63", "#8D239E", "#673AB7", "#3F51B5", "#253985", "#02A8F4", "#009688", "#8BC34A", "#FF9800", "#FE5622", "#795648", "#9E9E9E", "#617D8B","#E8ECFB")


library(SARTools)
target_adlt <- loadTargetFile(targetFile=targetFile, varInt=varInt, condRef=condRef, batch=batch)
target <- loadTargetFile(targetFile="target.txt", varInt=varInt, condRef=condRef, batch=batch)

```

```{r}
vst <- read_csv("AdultCount-vst.csv") %>% column_to_rownames("Id")
```
```{r}
#anno_df_biomart <- read_csv("annotation_mm10.csv")
```
```{r}
Periportal_FC4 <- read_csv("Periportal_FC4.txt")
Pericentral_FC4 <- read_csv("Pericentral_FC4.txt")
```

```{r}
df <- read_csv("ListDegs_Adult_NTC.csv")



myGeneSets <- list()

for (i in 1:length(colnames(df))){
  new_elements <- df[i]
  names(new_elements) <- colnames(df)[i]
  myGeneSets <- c(myGeneSets, new_elements)
}

myGeneSets <- modify_tree(myGeneSets, leaf = ~ discard(.x, is.na))


```
```{r}
upset(fromList(myGeneSets))
```

```{r fig.height=4, fig.width=10}
plot <- SARTools::PCAPlot(counts.trans=vst, group=target_adlt[,varInt], col=colors, outfile = F, ggplot_theme = theme_bw(), n=500)
```
```{r}
n=min(500, nrow(vst))
rv = apply(vst, 1, var, na.rm=TRUE)
pca = prcomp(t(vst[order(rv, decreasing = TRUE), ][1:n,]), rank = 3)
prp <- pca$sdev^2 * 100 / sum(pca$sdev^2)
#prp <- round(prp[1:length(prp)],2)
prp <- round(prp[1:3],2)
```

```{r}
colors <- c("#B80000","#B80000", "#E81E63", "#E81E63", "#8D239E", "#8D239E", "#673AB7", "#673AB7")#, "#3F51B5", "#3F51B5", "#253985", "#253985","#02A8F4", "#02A8F4", "#009688","#009688",  "#8BC34A", "#8BC34A", "#FF9800", "#FF9800", "#FE5622", "#FE5622", "#795648", "#795648","#9E9E9E", "#9E9E9E","#617D8B","#617D8B", "#E8ECFB", "#E8ECFB")

colors <- colors[1:length(colnames(vst[1:8]))]

# colors <- c("#6491c0","#6491c0","#6491c0",
#                      "#bd8fbd","#bd8fbd","#bd8fbd",
#                      "#ed8b56", "#ed8b56", "#ed8b56")#,
#                    #  "##2e68b1","##2e68b1","##2e68b1",
#                   #   "##bd8fbd", "##bd8fbd", "##bd8fbd")
labels <- rownames(plot)
colorsg <- setNames(colors,labels )
```

```{r}
sampleDists <- dist(t(vst))
```

```{r}
save_pheatmap_pdf <- function(x, filename, width=7, height=7) {
    stopifnot(!missing(x))
    stopifnot(!missing(filename))
    pdf(filename, width=width, height=height)
    x
    dev.off()
}
```


```{r fig.height=4, fig.width=5}
sampleDistMatrix <- as.matrix(sampleDists)
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)

p <- pheatmap(sampleDistMatrix,
         clustering_distance_rows=sampleDists,
         clustering_distance_cols=sampleDists,
         col=colors, 
         cellwidth=10, cellheight=10)
p
save_pheatmap_pdf(p, "Mathep_distanceMatrix.pdf")
```
```{r}
Allvst = read_csv("AllCount-vst.csv")
Allvst <- Allvst %>% column_to_rownames("Id")
```

```{r}
newdata <- Allvst[names(pca$center), 9:30]
dataPred=predict(pca,t(newdata))
pcaData<- rbind(pcaData,data.frame(dataPred))

```
```{r}


colors <- c("#B80000","#B80000", "#E81E63", "#E81E63", "#8D239E", "#8D239E", "#673AB7", "#673AB7", "#3F51B5", "#3F51B5", "#253985", "#253985","#02A8F4", "#02A8F4", "#009688","#009688",  "#8BC34A", "#8BC34A", "#FF9800", "#FF9800", "#FE5622", "#FE5622", "#795648", "#795648","#9E9E9E", "#9E9E9E","#617D8B","#617D8B", "#E8ECFB", "#E8ECFB")

colors <- colors[1:length(colnames(Allvst))]

# colors <- c("#6491c0","#6491c0","#6491c0",
#                      "#bd8fbd","#bd8fbd","#bd8fbd",
#                      "#ed8b56", "#ed8b56", "#ed8b56")#,
#                    #  "##2e68b1","##2e68b1","##2e68b1",
#                   #   "##bd8fbd", "##bd8fbd", "##bd8fbd")
labels <- rownames(pcaData)
colorsg <- setNames(colors,labels )
```

```{r fig.height=10, fig.width=10}
sampleDistsPCA <- dist(pcaData)
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)

p <- pheatmap(as.matrix(sampleDistsPCA),
         clustering_distance_rows=sampleDistsPCA,
         clustering_distance_cols=sampleDistsPCA,
         col=colors, 
         cellwidth=10, cellheight=10)
p

save_pheatmap_pdf(p, "Mathep_distanceMatrix_integrated.pdf")
```
```{r}
pc_loadings <- pca$rotation

pc_loadings <- pc_loadings %>% 
  as_tibble(rownames = "Id")

pc_loadings <- left_join(pc_loadings, anno_df_biomart, by = "Id")

# print the result

pc_loadings

```
```{r}
n = 5
topPCA_genes <- list()

top_genes_PC1 <- arrange(pc_loadings, desc(pc_loadings["PC1"])) %>% slice(1:n) %>% pull(gene_name) %>% unique()
top_genes_PC2 <- arrange(pc_loadings, desc(pc_loadings["PC2"])) %>% slice(1:n) %>% pull(gene_name) %>% unique()


top_neg_genes_PC1 <- arrange(pc_loadings, pc_loadings["PC1"]) %>% slice(1:n) %>% pull(gene_name) %>% unique()
top_neg_genes_PC2 <- arrange(pc_loadings, pc_loadings["PC2"]) %>% slice(1:n) %>% pull(gene_name) %>% unique()

topPCA_genes <- c(list(top_genes_PC1),
                  list(top_neg_genes_PC1),
                  list(top_genes_PC2),
                  list(top_neg_genes_PC2)
                  )

names(topPCA_genes) <- c("top_genes_PC1", "top_neg_genes_PC1", "top_genes_PC2", "top_neg_genes_PC2")
```


```{r}
inc <- function(x)
{
 eval.parent(substitute(x <- x + 1))
}

n=25

top25_PCA_genes <- list()

top25_genes_PC1 <- arrange(pc_loadings, desc(pc_loadings["PC1"])) %>% slice(1:n) %>% pull(gene_name) %>% unique()
top25_genes_PC2 <- arrange(pc_loadings, desc(pc_loadings["PC2"])) %>% slice(1:n) %>% pull(gene_name) %>% unique()

top25_neg_genes_PC1 <- arrange(pc_loadings, pc_loadings["PC1"]) %>% slice(1:n) %>% pull(gene_name) %>% unique()
top25_neg_genes_PC2 <- arrange(pc_loadings, pc_loadings["PC2"]) %>% slice(1:n) %>% pull(gene_name) %>% unique()

top25_PCA_genes <- c(list(top25_genes_PC1),
                  list(top25_neg_genes_PC1),
                  list(top25_genes_PC2),
                  list(top25_neg_genes_PC2)
                       )

names(top25_PCA_genes) <- c("top25_genes_PC1", "top25_neg_genes_PC1", "top25_genes_PC2", "top25_neg_genes_PC2")

print(top25_PCA_genes)

```
```{r}
Periportal_FC4 <- Periportal_FC4$Id
Pericentral_FC4 <- Pericentral_FC4$Id
```

```{r}
for(i in names(topPCA_genes)){
  write.csv(topPCA_genes[[i]], paste0(i,".csv"))
}

```

```{r fig.height=6, fig.width=6}

color_legend_min = -2
color_legend_max = 2
colors = colorRampPalette(rev(brewer.pal(7, "RdYlBu")))(7)

for (i in 1:length(topPCA_genes)){
  print(i)
  tidy_heatmap(MeansDEGSvstSC_l[which(MeansDEGSvstSC_l$gene_name %in% topPCA_genes[[i]]),],
             rows = gene_name,
             columns = Treatment,
             values = Expression,
             cellwidth = 12,
             cellheight = 12,
             cluster_rows = T,
             cluster_cols = T,
             clustering_distance_cols = sampleDistsPCA,
             color_legend_min = color_legend_min,
             color_legend_max = color_legend_max,
             colors = colors,
             main = paste0(names(topPCA_genes[i])),
             filename = paste0(names(topPCA_genes[i]), "_5.pdf")
             )
  
  
  
}
```
```{r fig.height=6, fig.width=6}

color_legend_min = -2
color_legend_max = 2
colors = colorRampPalette(rev(brewer.pal(7, "RdYlBu")))(7)

for (i in 1:length(top10_PCA_genes_ID)){
  print(i)
  tidy_heatmap(MeansDEGSvstSC_l[which(MeansDEGSvstSC_l$Id %in% top10_PCA_genes_ID[[i]]),],
             rows = gene_name,
             columns = Treatment,
             values = Expression,
             cellwidth = 12,
             cellheight = 12,
             cluster_rows = T,
             cluster_cols = T,
             clustering_distance_cols = sampleDistsPCA,
             color_legend_min = color_legend_min,
             color_legend_max = color_legend_max,
             colors = colors,
             main = paste0(names(top10_PCA_genes_ID[i])),
             filename = paste0(names(top10_PCA_genes_ID[i]), "_top50.pdf")
             )
  
  
  
}
```

```{r fig.height=6, fig.width=6}

color_legend_min = -2
color_legend_max = 2
colors = colorRampPalette(rev(brewer.pal(7, "RdYlBu")))(7)

for (i in 1:length(top10_PCA_genes_ID)){
  print(i)
  tidy_heatmap(MeansDEGSvstSC_l[which(MeansDEGSvstSC_l$Id %in% top10_PCA_genes_ID[[i]]),],
             rows = gene_name,
             columns = Treatment,
             values = Expression,
             cellwidth = 12,
             cellheight = 12,
             cluster_rows = T,
             cluster_cols = T,
             clustering_distance_cols = sampleDistsPCA,
             color_legend_min = color_legend_min,
             color_legend_max = color_legend_max,
             colors = colors,
             main = paste0(names(top10_PCA_genes_ID[i])),
             filename = paste0(names(top10_PCA_genes_ID[i]), "_top10.pdf")
             )
  
  
  
}
```



```{r fig.height=8, fig.width=6}

tidy_heatmap(MeansDEGSvstSC_l[which(MeansDEGSvstSC_l$gene_name %in% Periportal_FC4),],
             rows = gene_name,
             columns = Treatment,
             values = Expression,
             cellwidth = 12,
             cellheight = 5,
             cluster_rows = T,
             color_legend_min = color_legend_min,
             color_legend_max = color_legend_max,
             colors = colors,
             fontsize = 6,
             main = "Periportal_FC4"
               )

tidy_heatmap(MeansDEGSvstSC_l[which(MeansDEGSvstSC_l$gene_name %in% Pericentral_FC4),],
             rows = gene_name,
             columns = Treatment,
             values = Expression,
             cellwidth = 12,
             cellheight = 5,
             cluster_rows = T,
             colors = colors,
             color_legend_min = color_legend_min,
             color_legend_max = color_legend_max,
             fontsize = 6,
             main = "Pericentral_FC4"
               )

```

```{r}
pcaData.Centroid <- read_csv("pcaData.Centroid.csv") %>% column_to_rownames("Sample")
```

```{r fig.height=3, fig.width=8}


colorSinglesample <- c("#B80000", "#E81E63", "#8D239E",  "#673AB7",  "#3F51B5", "#253985", "#02A8F4", "#009688",  "#8BC34A", "#FF9800",  "#FE5622", "#795648", "#9E9E9E","#617D8B", "#E8ECFB")

colorSinglesample <- colorSinglesample[1:length(rownames(pcaData.Centroid))]

# colors <- c("#6491c0","#6491c0","#6491c0",
#                      "#bd8fbd","#bd8fbd","#bd8fbd",
#                      "#ed8b56", "#ed8b56", "#ed8b56")#,
#                    #  "##2e68b1","##2e68b1","##2e68b1",
#                   #   "##bd8fbd", "##bd8fbd", "##bd8fbd")
labels <- rownames(rownames(pcaData.Centroid))
colorSinglesample <- setNames(colorSinglesample,labels )


p <- ggplot(pcaData.Centroid, aes(PC1, PC2, color=colorSinglesample)) +
  geom_point(size=3) +
  xlab(paste0("PC1: ",prp[1],"% variance")) +
  ylab(paste0("PC2: ",prp[2],"% variance")) + 
  coord_fixed() +
  theme_bw() + 
   theme(aspect.ratio = 1, legend.position = "none", panel.grid.major = element_blank() , panel.grid.minor = element_blank())
pg<- LabelPoints(plot = p, points = labels, repel = T, min.segment.length = 0, box.padding = 0.5, max.overlaps = Inf)
p2 <- ggplot(pcaData.Centroid, aes(PC1, PC3, color=colorSinglesample)) +
  geom_point(size=3) +
  xlab(paste0("PC1: ",prp[1],"% variance")) +
  ylab(paste0("PC3: ",prp[3],"% variance")) + 
  coord_fixed() +
  theme_bw() + 
  theme(aspect.ratio = 1, legend.position = "none", panel.grid.major = element_blank() , panel.grid.minor = element_blank())
pg2<- LabelPoints(plot = p2, points = labels, repel = T, min.segment.length = 0, box.padding = 0.5, max.overlaps = Inf)

p3 <- ggplot(pcaData.Centroid, aes(PC2, PC3, color=colorSinglesample)) +
  geom_point(size=3) +
  xlab(paste0("PC2: ",prp[2],"% variance")) +
  ylab(paste0("PC3: ",prp[3],"% variance")) + 
  coord_fixed() +
  theme_bw() + 
  theme(aspect.ratio = 1, legend.position = "none", panel.grid.major = element_blank() , panel.grid.minor = element_blank())
pg3<- LabelPoints(plot = p3, points = labels, repel = T, min.segment.length = 0, box.padding = 0.5, max.overlaps = Inf)

plot_grid(ncol = 3, pg, pg2, pg3)
```
```{r fig.height=4, fig.width=6}
sampleDistsPCA <- dist(pcaData.Centroid)
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)

pdf("Mathep_distanceMatrix_singleSample.pdf", width=7, height=7)



p <- pheatmap(as.matrix(sampleDistsPCA),
         clustering_distance_rows=sampleDistsPCA,
         clustering_distance_cols=sampleDistsPCA,
         col=colors, 
         cellwidth=10, cellheight=10)
p

dev.off()
#save_pheatmap_pdf(p, "Mathep_distanceMatrix_singleSample.pdf")
```


```{r}
top_pos_genes <- pc_loadings %>% 
  # select only the PCs we are interested in
  dplyr::select(Id, gene_name, PC1, PC2) %>%
  # convert to a "long" format
  pivot_longer(matches("PC"), names_to = "PC", values_to = "loading") %>% 
  # for each PC
  group_by(PC) %>%
  # arrange by descending order of loading
  arrange(desc(abs(loading))) %>%
  # take the 10 top rows
  slice(1:10) %>%
  # pull the gene column as a vector
  pull(gene_name) %>%
  # ensure only unique genes are retained
  unique()

top_neg_genes <- pc_loadings %>% 
  # select only the PCs we are interested in
  dplyr::select(Id, gene_name, PC1, PC2) %>%
  # convert to a "long" format
  pivot_longer(matches("PC"), names_to = "PC", values_to = "loading") %>% 
  # for each PC
  group_by(PC) %>%
  # arrange by descending order of loading
  arrange(abs(loading)) %>%
  # take the 10 top rows
  slice(1:10) %>%
  # pull the gene column as a vector
  pull(gene_name) %>%
  # ensure only unique genes are retained
  unique()

top_genes <- unique(c(top_neg_genes, top_pos_genes))
```

```{r}
color_legend_min = -2
color_legend_max = 2
colors = colorRampPalette(rev(brewer.pal(9, "RdYlBu")))(9)

tidy_heatmap(MeansDEGSvstSC_l[which(MeansDEGSvstSC_l$gene_name %in% top_genes),],
             rows = gene_name,
             columns = Treatment,
             values = Expression,
             cellwidth = 12,
             cellheight = 5,
             cluster_rows = T,
             cluster_cols = T,
             clustering_distance_cols = sampleDistsPCA,
             colors = colors,
             color_legend_min = color_legend_min,
             color_legend_max = color_legend_max,
             fontsize = 6,
             main = "Top PCA genes",
             #filename = "tidy_heatmap_TopPCA_genes.pdf"
               )

```

```{r}
library(gprofiler2)

Periportal_FC4_Id <- gconvert(Periportal_FC4, organism="mmusculus", target="ENSG", filter_na = F)$target
Pericentral_FC4_Id <- gconvert(Pericentral_FC4, organism="mmusculus", target="ENSG", filter_na = F)$target
```

```{r}
n = 50
top10_PCA_genes_ID <- list()

top10_genes_PC1 <- arrange(pc_loadings, desc(pc_loadings["PC1"])) %>% slice(1:n) %>% pull(Id) %>% unique()
top10_genes_PC2 <- arrange(pc_loadings, desc(pc_loadings["PC2"])) %>% slice(1:n) %>% pull(Id) %>% unique()

top10_neg_genes_PC1 <- arrange(pc_loadings, pc_loadings["PC1"]) %>% slice(1:n) %>% pull(Id) %>% unique()
top10_neg_genes_PC2 <- arrange(pc_loadings, pc_loadings["PC2"]) %>% slice(1:n) %>% pull(Id) %>% unique()

top10_PCA_genes_ID <- c(list(top10_genes_PC1),
                  list(top10_neg_genes_PC1),
                  list(top10_genes_PC2),
                  list(top10_neg_genes_PC2),
                  list(Pericentral_FC4_Id),
                  list(Periportal_FC4_Id)
                       )

names(top10_PCA_genes_ID) <- c("top10_genes_PC1", "top10_neg_genes_PC1", "top10_genes_PC2", "top10_neg_genes_PC2", "Pericentral_FC4", "Periportal_FC4")
```

##Calculate TPM
```{r}
#' @title Compute TPM from a read count matrix
#' @param counts A numeric data.frame of read counts with samples (columns) and genes (rows).
#' @param len A vector of gene cds length equal to number of rows of dfr.
#'
#' https://support.bioconductor.org/p/91218/
#'
tpm <- function(counts,len) {
  x <- counts/len
  return(t(t(x)*1e6/colSums(x)))
}
```

```{r}
gene_meta <- read_csv("/Users/magalhae/Desktop/Atshuhiro/RNAseq_20240423/AllvsAll/MatHep_Gene_metadata.csv") %>% column_to_rownames("Id")
Allcount_bc <- read_csv("/Users/magalhae/Desktop/Atshuhiro/RNAseq_20240423/AllvsAll/AllCount-batchCorrected.csv") %>% column_to_rownames("Id")

# remove genes with low counts
keep_genes <- rowSums( Allcount_bc > 50 ) >= 3
Allcount_bc <- Allcount_bc[keep_genes,]

igenes <- intersect(rownames(Allcount_bc),rownames(gene_meta))
gene_meta1 <- gene_meta[igenes,]
Allcount_bc1 <- Allcount_bc[igenes,]
all.equal(rownames(Allcount_bc1),rownames(gene_meta))
```
```{r}
Allcount_bc_TPM <- tpm(Allcount_bc1,gene_meta1$Length)
Allcount_bc_logTPM <- log2( Allcount_bc_TPM + 1 )
```
```{r}
boxplot(Allcount_bc_logTPM ,ylab=expression('Log'[2]~'Read counts'),las=2,main="TPM")
```

```{r}
longAllTPM <- as.data.frame(Allcount_bc_TPM) %>% rownames_to_column("Id") %>% gather("group", "TPM_Expression", -Id)
longAllTPM <- longAllTPM %>% left_join(anno_df_biomart, by = "Id") %>% 
  left_join(target[,c("Label", "Treatment")], by = c("group" = "Label"))

MeansAllTPM  <- longAllTPM %>%
  group_by(Id, Treatment) %>%
  summarize(TPM_MeanExpr = mean(TPM_Expression))

MeansAllTPM  <- MeansAllTPM %>%
  spread(., Treatment, TPM_MeanExpr) %>%
  column_to_rownames("Id")
write.csv(MeansAllTPM, file= "MeansAllTPM_bc.csv")

MeansAll_logTPM <- log2( MeansAllTPM + 1 )
write.csv(MeansAll_logTPM, file= "MeansAll_logTPM.csv")
```
```{r}
boxplot(MeansAll_logTPM ,ylab=expression('Log'[2]~'Read counts'),las=2,main="TPM")
```


```{r}
#library(GSVA)
ssgseaPar <- ssgseaParam(as.matrix(MeansAll_logTPM),top10_PCA_genes_ID)
ssgsea.es <- gsva(ssgseaPar, verbose=FALSE)
gsvaPar <- gsvaParam(as.matrix(MeansAll_logTPM),top10_PCA_genes_ID, kcdf = "Gaussian", maxDiff = T )
gsva.es <- gsva(gsvaPar, verbose=FALSE)


h1 <- Heatmap(ssgsea.es,
             name = "ssGSEA", #title of legend
             col = viridis(5, option = "D"),
             #col = colorRampPalette( rev(brewer.pal(15, "PiYG")) )(15),
             #col = colorRampPalette((brewer.pal(n = 10, name ="RdBu")))(10),
             cluster_rows = F,
             #column_order = order(as.numeric(gsub("column", "", colnames(mat)))),
             cluster_columns = T,
             show_row_names = TRUE,
             cluster_row_slices = FALSE,
             width = unit(6, "cm") , height = unit(3, "cm")
             )
h1 = draw(h1)
```
```{r}

h2 <- Heatmap(gsva.es,
             name = "GSVA", #title of legend
             #col = viridis(5, option = "D"),
             col = colorRampPalette(c("#7FBFF5", "#F1F1F1", "#F8A29E"))(9),
             #col = diverging_hcl(n = 5, palette ="Berlin", rev = F),
             #col = colorRampPalette( rev(brewer.pal(15, "PiYG")) )(15),
             #col = colorRampPalette((brewer.pal(n = 10, name ="RdBu")))(10),
             cluster_rows = F,
             cluster_columns = T,
             show_row_names = TRUE,
             cluster_row_slices = FALSE,
             width = unit(0.75, "snpc") , height = unit(0.3, "snpc")
             )
h2 = draw(h2)
```

```{r}
gsva.esTest <- data.frame(gsva.es) %>% rownames_to_column("ScoreList") %>%  gather("Sample", "GSVA_score", -ScoreList,)


tidy_heatmap(gsva.esTest,
             rows = ScoreList,
             columns = Sample,
             values = GSVA_score,
             cellwidth = 12,
             cellheight = 12,
             cluster_rows = F,
             cluster_cols = T,
             clustering_distance_cols = sampleDistsPCA,
             color_legend_min = -1,
             color_legend_max = 1,
             #colors = colorRampPalette(rev(brewer.pal(n = 11, name ="PiYG")))(11),
             #colors = viridis(25, option = "D"),
             colors = diverging_hcl(n = 256, palette ="Berlin", rev = F),
             color_legend_n =256,
             main = "GSVA",
             filename ="GSVA_PCA_TPM.pdf"
             )


```
```{r}
assign('ssgsea.scores', ssgsea(as.matrix(MeansAllvst), top10_PCA_genes_ID, scale = T, norm = F))

ssgsea.scores <- data.frame(ssgsea.scores) %>% rownames_to_column("ScoreList") %>%  gather("Sample", "ssGSEA_score", -ScoreList,)

```
```{r}
tidy_heatmap(ssgsea.scores,
             rows = ScoreList,
             columns = Sample,
             values = ssGSEA_score,
             cellwidth = 12,
             cellheight = 12,
             cluster_rows = F,
             cluster_cols = T,
             clustering_distance_cols = sampleDistsPCA,
             color_legend_min = 0,
             color_legend_max = 0.5,
             #colors = colorRampPalette(rev(brewer.pal(n = 11, name ="PiYG")))(11),
             #colors = viridis(25, option = "D"),
             colors = sequential_hcl(n = 5, palette ="BuGn",rev = T),
             main = "ssgsea scorering",
             filename ="GSVA_PCA2.pdf"
             )

tidy_heatmap(ssgsea.scores,
             rows = ScoreList,
             columns = Sample,
             values = ssGSEA_score,
             cellwidth = 12,
             cellheight = 12,
             cluster_rows = F,
             cluster_cols = T,
             clustering_distance_cols = sampleDistsPCA,
             color_legend_min = 0,
             color_legend_max = 0.5,
             #colors = colorRampPalette(rev(brewer.pal(n = 11, name ="PiYG")))(11),
             #colors = viridis(25, option = "D"),
             colors = sequential_hcl(n = 11, palette ="PuRd",rev = T),
             main = "ssgsea scorering",
             filename ="GSVA_PCA1.pdf"
             )
```


